fix the bug instead of trigger behaves wrongly in recursively call
babelfish-for-postgresql/postgresql_modified_for_babelfish pull request #31
Opened 2022-06-24 22:31 UTC by forestkeeper

recursively call the instead of trigger may lose the last DML to the triggered table

in previous impl, recursively trig a instead of trigger will not do any
changes into the trigged table, as for the last triggered DML, it
shouldn't do the instead of procedure do, what it should do is to do data change into
the table, since the last trigger should not be triggered if it's
recursively triggered

### Description

```
-- repro in Babelfish:
1>
2> CREATE TABLE t
3> (
4> c1 int IDENTITY(1,1) PRIMARY KEY,
5> c2 varchar(20) UNIQUE,
6> );
7>
8> INSERT INTO t(c2)
9> VALUES ('Joe'), ('Steve');
10>
11>
12> SELECT * FROM t
13> GO
c1          c2
----------- --------------------
          1 Joe
          2 Steve
1>
2> CREATE TRIGGER TR_t ON t
3> INSTEAD OF INSERT
4> AS
5>  DECLARE @c1 int, @c2 varchar(20)
6> SELECT @c1 = c1, @c2 = c2 FROM inserted
7> INSERT INTO t (c2) VALUES(@c2 + '2') --BUG: This INSERT disappears
8> GO
1>
2> INSERT INTO t(c2) VALUES ('Joe')
3> GO
1>
2> --There should be 3 rows, but there are only 2 rows. The INSERT from within the trigger is lost.
3> SELECT * FROM t
4> GO
c1          c2
----------- --------------------
          1 Joe
          2 Steve
```

```
--Babelfish:
1> CREATE TABLE t
2> (
3> c1 int IDENTITY(1,1) PRIMARY KEY,
4> c2 varchar(20),
5> );
6> INSERT INTO t(c2)
7> VALUES ('Joe'), ('Steve');
8> SELECT 'Base data, 2 rows:', * FROM t
9> GO
                 c1          c2
------------------------------------------------------------------------------------
------------------------------------------------------------------------------------
---------------- ----------- --------------------
Base data, 2 rows:                           1 Joe
Base data, 2 rows:                           2 Steve

1> --DELETE on same table from INSTEAD OF DELETE trigger isn't persisted
2> CREATE TRIGGER tr_txz ON t
3> INSTEAD OF DELETE
4> AS
5> DELETE FROM t WHERE c2 IN(SELECT c2 FROM deleted)
6> SELECT '@@ROWCOUNT from the DELETE trigger, the value should be 1', @@ROWCOUNT
7> GO

1> --BUG: Delete on same table from DELETE trigger isn't persisted
2> DELETE FROM t WHERE c2 = 'Steve'
3> GO
                 rowcount
------------------------------------------------------------------------------------
------------------------------------------------------------------------------------
---------------- -----------
@@ROWCOUNT from the DELETE trigger, the value should be 1                           0

1> SELECT 'DELETE done from DELETE trigger, should be 1 row, Joe', * FROM t
2> GO
                 c1          c2
------------------------------------------------------------------------------------
------------------------------------------------------------------------------------
---------------- ----------- --------------------
DELETE done from DELETE trigger, should be 1 row, Joe                           1 Joe
DELETE done from DELETE trigger, should be 1 row, Joe                           2 Steve

```

when in recursively calling inside the last trigger insert/delete/update will be lost
 
### Issues Resolved

when recursively call , the last called instead of trigger should stop calling new ones, then the insert/delete/update stmt will be persisted into real table
 
### Check List

- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the PostgreSQL license, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/postgresql_modified_for_babelfish/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-06-24 22:35 UTC, macwoody approved these changes, later dismissed

2022-06-27 06:31 UTC, surendravishnoi requested changes
Please improve commit message

2022-06-27 07:17 UTC, surendravishnoi approved these changes

2022-06-27 07:30 UTC, kuntalghosh reviewed
Please mention the extension PR that adds tests for the same PR. Also, please mention the JIRA in the commit message.

2022-06-27 17:37 UTC, sangilsong approved these changes

2022-06-27 17:45 UTC, merged