Support Table and Index partitioning in Babelfish
babelfish-for-postgresql/postgresql_modified_for_babelfish pull request #399
Opened 2024-07-01 11:14 UTC by sumitj824

### Description

[Describe what this change achieves]
 
### Issues Resolved

[List any issues this PR will resolve]
 
### Check List

- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the PostgreSQL license, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/postgresql_modified_for_babelfish/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2024-07-08 08:03 UTC, Deepesh125 requested changes

2024-07-08 08:03 UTC, Deepesh125 commented on src/backend/access/common/reloptions.c
> +		if (pltsql_partitioned_table_reloptions_hook && pltsql_partitioned_table_reloptions_hook(reloptions))
check dialect also

2024-07-08 08:17 UTC, sumitj824 commented on src/backend/access/common/reloptions.c
> +		if (pltsql_partitioned_table_reloptions_hook && pltsql_partitioned_table_reloptions_hook(reloptions))
Dialect check and dump/restore check are already there within the underlined extension function for the this hook.

2024-07-12 12:13 UTC, rishabhtanwar29 approved these changes

2024-07-15 12:34 UTC, Deepesh125 requested changes

2024-07-15 12:34 UTC, Deepesh125 commented on src/backend/parser/parse_utilcmd.c
> +			(!bbf_dump_restore || strcmp(bbf_dump_restore, "on") != 0))
We should check if parent rel is partitioned table

2024-07-18 23:45 UTC, forestkeeper commented on src/backend/access/common/reloptions.c
> +		/* For babelfish partitioned table, allow usage of reloptions in TSQL dialect. */
The comment style should be : 

```
/* 
 * For babelfish partitioned table, allow usage of reloptions in TSQL dialect. 
 */
```

2024-07-18 23:47 UTC, forestkeeper commented on src/backend/access/common/reloptions.c
> +		if (pltsql_partitioned_table_reloptions_hook && pltsql_partitioned_table_reloptions_hook(reloptions))
Should give a more reasonable name for the hook type like : 
```
pltsql_is_partitioned_table_reloptions_allowed_hook
```
the current name looks confusing.

2024-07-22 04:06 UTC, Deepesh125 approved these changes

2024-07-25 15:17 UTC, KushaalShroff approved these changes

2024-07-25 15:18 UTC, merged