Store create date in pg_class reloptions
babelfish-for-postgresql/postgresql_modified_for_babelfish pull request #48
Opened 2022-09-19 09:12 UTC by rishabhtanwar29

Task: BABEL-3010
Signed-off-by: Rishabh Tanwar <ritanwar@amazon.com>
 
### Check List

- [X] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the PostgreSQL license, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/postgresql_modified_for_babelfish/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-09-22 15:53 UTC, Deepesh125 approved these changes

2022-09-25 17:36 UTC, surendravishnoi approved these changes
Have we added tests for these?

2022-09-26 08:23 UTC, surendravishnoi approved these changes

2022-09-30 05:25 UTC, surendravishnoi requested changes
Please match the commit message with one for extension PR, may be we can put extension PR link here as well

2022-09-30 10:07 UTC, surendravishnoi approved these changes

2022-10-07 11:34 UTC, merged