Support duplicate trigger name in different database
babelfish-for-postgresql/postgresql_modified_for_babelfish pull request #50
Opened 2022-10-07 21:48 UTC by ZhenyeLee

Support duplicate trigger name in different database

Task:BABEL-3117
Signed-off-by: Zhenye Li <zhenye@amazon.com>

### Description
Previously, duplicate trigger name is not allowed in different database. But in sql server, different database can have the same trigger name. In this PR, we check if the trigger with the same trigger is not in current database, then the trigger can be created. And when drop trigger, we modified the pre check trigger in parsing stage to not throw error, and find the correct trigger to drop with trigger and database name. In this PR, we make `get_object_address_trigger_tsql` a hook type and move the function to hook.c file.
 
### Issues Resolved

BABEL-3117
 
### Check List

- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the PostgreSQL license, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/postgresql_modified_for_babelfish/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-10-09 17:02 UTC, surendravishnoi commented on src/backend/catalog/objectaddress.c
> +				if(sql_dialect == SQL_DIALECT_TSQL && get_trigger_object_address_hook)
let us move dialect check inside hook, that way engine code is free of TSQL reference

2022-10-14 19:54 UTC, AvantikaDG requested changes

2022-10-14 19:54 UTC, AvantikaDG commented on src/backend/catalog/objectaddress.c
> +				if(get_trigger_object_address_hook){
I would suggest adding a check for sql_dialect here instead of returning random values from the hook function if dialect is not tsql.

2022-10-14 19:54 UTC, AvantikaDG commented on src/backend/catalog/objectaddress.c
> -
You raised the bar on best practices + quality by removing this code from the engine and replacing it with a hook. Great job!

2022-10-14 19:59 UTC, AvantikaDG commented on src/backend/catalog/objectaddress.c
> +				if(get_trigger_object_address_hook){
Just saw Surendra's comment - I am fine with having it inside the hook function.

2022-10-14 21:21 UTC, forestkeeper reviewed
LGTM

2022-10-14 21:22 UTC, forestkeeper reviewed
LGTM

2022-10-27 20:42 UTC, AvantikaDG approved these changes

2022-10-27 20:42 UTC, merged