Support nondeterministic collations for LIKE in CHECK constraint clause
babelfish-for-postgresql/postgresql_modified_for_babelfish pull request #51
Opened 2022-10-11 03:11 UTC by AvantikaDG

Utility statements such as ALTER TABLE are not planned. Due to collation like to ilike transformation logic being called in a planner hook, CHECK constraint in utlity commands do not support LIKE for nondeterministic collations.

To solve this problem, we add a hook to invoke the like to ilike transformation function after the raw parsetree is transformed into an executable expression.

Task: BABEL-3319
Signed-off-by: Avantika Dasgupta <davantik@amazon.com>

2022-10-11 13:21 UTC, Deepesh125 requested changes

2022-10-11 13:21 UTC, Deepesh125 commented on src/backend/catalog/heap.c
> +	if(IsA(raw_constraint, A_Expr) && ((A_Expr*)raw_constraint)->kind == AEXPR_LIKE
I think, It would be better to have dialect check as well.

2022-10-11 17:14 UTC, 2jungkook commented
Please add an extension PR link to the description (same for the extension PR description).

2022-11-02 23:19 UTC, 2jungkook commented on src/backend/catalog/heap.c
> +	 * statements do not get planned, we invoke a planner hook here to carry out the
planner hook?

2022-11-02 23:19 UTC, 2jungkook commented on src/backend/catalog/heap.c
> +#include "nodes/nodes.h"
why do we need this?

2022-11-03 18:51 UTC, 2jungkook approved these changes

2022-11-04 06:19 UTC, Deepesh125 approved these changes

2022-11-11 23:56 UTC, merged