Support T-SQL Linked Servers
babelfish-for-postgresql/postgresql_modified_for_babelfish pull request #72
Opened 2022-12-15 13:24 UTC by thephantomthief

### Description
In this commit, we added a hook to bypass permission checks for foreign
data wrapper if the babelfishpg_tsql extension is installed and the user
sysadmin of Babelfish db.

Task: BABEL-861
Signed-off-by: Sharu Goel <goelshar@amazon.com>
 
### Check List

- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the PostgreSQL license, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/postgresql_modified_for_babelfish/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2022-12-30 11:02 UTC, kuntalghosh requested changes

2022-12-30 11:02 UTC, kuntalghosh commented on src/backend/catalog/aclchk.c
> +	if (tsql_has_linked_srv_permissions_hook && (*tsql_has_linked_srv_permissions_hook)(roleid))
I think we can avoid this change completely by granting sysadmin for a specific foreign server usage.
```
GRANT USAGE ON FOREIGN SERVER foreigndb_fdw TO sysadmin;
```
While creating the foreign server, you can grant the above permission.

2023-01-05 08:20 UTC, thephantomthief commented on src/backend/catalog/aclchk.c
> +	if (tsql_has_linked_srv_permissions_hook && (*tsql_has_linked_srv_permissions_hook)(roleid))
executing the SQL alone won't suffice. We also need permission on the FDW itself. I tried executing `GRANT USAGE ON FOREIGN DATA WRAPPER tds_fdw TO sysadmin;`  additionally, but I still get "permission denied for foreign data wrapper tds_fdw"

2023-01-06 13:28 UTC, kuntalghosh approved these changes

2023-01-09 06:45 UTC, merged