Support T-SQL OPENQUERY
babelfish-for-postgresql/postgresql_modified_for_babelfish pull request #84
Opened 2023-01-20 09:44 UTC by thephantomthief

### Description

This commit adds a hook in the engine where we compute the tuple
descriptor from the SQL definition of a table function. If the function
is OPENQUERY, we will connect to the remote server and fetch the 
column metadata using sp_describe_first_result_set stored procedure.
Using this we modify the tuple descriptor in the analyzer and execution 
phase so that it matches with the actual result set when we run the actual
query.

Signed-off-by: Sharu Goel <goelshar@amazon.com>
 
### Check List

- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is under the terms of the PostgreSQL license, and grant any person obtaining a copy of the contribution permission to relicense all or a portion of my contribution to the PostgreSQL License solely to contribute all or a portion of my contribution to the PostgreSQL open source project.

For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/babelfish-for-postgresql/postgresql_modified_for_babelfish/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

2023-01-20 13:59 UTC, kuntalghosh requested changes

2023-01-20 13:59 UTC, kuntalghosh commented on src/backend/utils/fmgr/funcapi.c
> +		if (funcname && (strlen(funcname) == 9) && strncmp(NameStr(procform->proname), "openquery", 9) == 0)
This check should be moved inside the extension.

2023-01-24 04:11 UTC, Deepesh125 requested changes

2023-01-24 04:11 UTC, Deepesh125 commented on src/backend/utils/fmgr/funcapi.c
> +		if (funcname && (strlen(funcname) == 9) && strncmp(funcname, "openquery", 9) == 0)
we can save some overhead on PG by moving this operations inside hook impl. And, should it be strncasecmp?

2023-01-24 04:11 UTC, Deepesh125 commented on src/backend/utils/fmgr/funcapi.c
> +	modify_RangeTblFunction_tupdesc_hook = NULL;
Please fix indentation

2023-01-24 04:11 UTC, Deepesh125 commented on src/backend/executor/nodeFunctionscan.c
> +#include "catalog/pg_proc.h"
why do we need this?

2023-01-24 04:11 UTC, Deepesh125 commented on src/backend/parser/parse_relation.c
> +#include "executor/nodeFunctionscan.h"
why do we need this?

2023-02-01 12:19 UTC, kuntalghosh approved these changes

2023-02-01 13:02 UTC, Deepesh125 approved these changes

2023-02-01 13:14 UTC, merged